name: Integration
on:
  pull_request:
    types: [locked]

jobs:
  integration-tests:
    name: AWS Deployment Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run compile
      - run: npm run integration --stream
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BOT_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BOT_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1